version: '3'

services:
  seafile:
    image: frikinet/seafile-pi4-sqlite
    restart: always
    volumes:
      - /mnt/usb256/seafile:/shared # <-- Permanent data are stored in external drive
    depends_on:
