version: '3'

services:
  seafile:
    image: frikinet/seafile-pi4-sqlite
    container_name: seafile
    environment:
      - PUID=1005
      - PGID=1005
      - TZ=Europe/Madrid
    restart: always
    volumes:
      - /mnt/usb256/seafile:/shared # <-- Permanent data are stored in external drive
    ports:
      - 8000:8000
      - 8082:8082
      - 8083:8083
    depends_on:
